# Generated by Django 4.1.7 on 2023-07-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doc',
            field=models.FileField(default=None, upload_to='uploads'),
        ),
    ]
