# Generated by Django 4.1.7 on 2023-07-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_employee', '0002_alter_employee_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='doc',
        ),
    ]
