# Generated by Django 4.1.7 on 2023-07-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp_employee', '0003_remove_employee_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='storage/')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp_employee.employee')),
            ],
        ),
    ]
