# Generated by Django 4.1.7 on 2023-07-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_employee', '0004_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='doc',
            new_name='pdf',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='emp',
        ),
    ]
