# Generated by Django 4.1.7 on 2023-07-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp_employee', '0005_rename_doc_upload_pdf_remove_upload_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='pdf',
        ),
        migrations.AddField(
            model_name='upload',
            name='doc',
            field=models.FileField(default='none', upload_to='storage/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='emp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tp_employee.employee'),
            preserve_default=False,
        ),
    ]
