# Generated by Django 4.1.7 on 2023-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_employee', '0006_remove_upload_pdf_upload_doc_upload_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
